### ISSUE TITLE
Help Menu exists but does not do anything

### ISSUE THREAD

**Issue by tperfitt** [ninxsoft/Bombardier#3]
The help menu in  version 2.0 does just shows this message:

<img width="420" alt="image" src="https://user-images.githubusercontent.com/2488947/71485042-f8445800-27d4-11ea-84d3-8dc2f5e221f8.png">

Have it go to the github site or remove the menu. I like the option to go to the github site.

**Comment by ninxsoft** [comment]
Fixed in #8, the Help menu now redirects to the GitHub project.
