### ISSUE TITLE
Thank you so much!

### ISSUE THREAD

**Issue by karinassuni** [ninxsoft/Bombardier#7]
This software provided me just what I needed to get Windows drivers for my MacBook Pro. For some reason, downloading the drivers through Boot Camp Assistant failed with an error, but your software didn't. Thank you so much for making it!

**Comment by ninxsoft** [comment]
You are most welcome!

If you ever need to grab drivers in the future, check out the new version:

https://github.com/ninxsoft/Bombardier/releases/tag/v3.0
